[colors.primary]
background = "#2A241A"
foreground = "#E8E8E8"
dim_foreground = "#B8B8B8"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#2A241A"
cursor = "#C0C0C0"

[colors.vi_mode_cursor]
text = "#2A241A"
cursor = "#FFFFFF"

[colors.search.matches]
foreground = "#2A241A"
background = "#B8B8B8"

[colors.search.focused_match]
foreground = "#2A241A"
background = "#E8E8E8"

[colors.footer_bar]
foreground = "#2A241A"
background = "#B8B8B8"

[colors.hints.start]
foreground = "#2A241A"
background = "#C0C0C0"

[colors.hints.end]
foreground = "#2A241A"
background = "#B8B8B8"

[colors.selection]
text = "#2A241A"
background = "#C0C0C0"

[colors.normal]
black = "#1A1A1A"
red = "#D0A060"
green = "#A0D060"
yellow = "#E0C060"
blue = "#8ABADD"
magenta = "#C08ABA"
cyan = "#8ACACA"
white = "#E8E8E8"

[colors.bright]
black = "#4A4A4A"
red = "#E0B070"
green = "#B0E070"
yellow = "#F0D070"
blue = "#9ACADD"
magenta = "#D09ACA"
cyan = "#9ADADA"
white = "#FFFFFF"

[colors.dim]
black = "#0F0F0F"
red = "#B08A50"
green = "#80B050"
yellow = "#C0A050"
blue = "#6A9ABB"
magenta = "#A06A9A"
cyan = "#6ABAAA"
white = "#B8B8B8"