[colors.primary]
background = "#1A1A1A"
foreground = "#EF7C3E"
dim_foreground = "#B6603E"
bright_foreground = "#FFA347"

[colors.cursor]
text = "#1A1A1A"
cursor = "#EF7C3E"

[colors.vi_mode_cursor]
text = "#1A1A1A"
cursor = "#FFA347"

[colors.search.matches]
foreground = "#1A1A1A"
background = "#B6603E"

[colors.search.focused_match]
foreground = "#1A1A1A"
background = "#EF7C3E"

[colors.footer_bar]
foreground = "#1A1A1A"
background = "#B6603E"

[colors.hints.start]
foreground = "#1A1A1A"
background = "#EF7C3E"

[colors.hints.end]
foreground = "#1A1A1A"
background = "#B6603E"

[colors.selection]
text = "#1A1A1A"
background = "#D76D3C"

[colors.normal]
black = "#0D0D0D"
red = "#D76D3C"
green = "#5A8B3A"
yellow = "#EF7C3E"
blue = "#4A6A9A"
magenta = "#8B5A7A"
cyan = "#5A8B8B"
white = "#EF7C3E"

[colors.bright]
black = "#3A3A3A"
red = "#FF8C4C"
green = "#7ACB5A"
yellow = "#FFA347"
blue = "#6A8ACA"
magenta = "#BB7AAA"
cyan = "#7ACBCB"
white = "#FFA347"

[colors.dim]
black = "#0A0A0A"
red = "#8F4C3D"
green = "#3A5A2A"
yellow = "#B6603E"
blue = "#2A4A6A"
magenta = "#5A3A4A"
cyan = "#3A5A5A"
white = "#B6603E"