[colors.primary]
background = "#F5F1E8"
foreground = "#703E3E"
dim_foreground = "#8F4C3D"
bright_foreground = "#5A2D2D"

[colors.cursor]
text = "#F5F1E8"
cursor = "#B6603E"

[colors.vi_mode_cursor]
text = "#F5F1E8"
cursor = "#D76D3C"

[colors.search.matches]
foreground = "#F5F1E8"
background = "#B6603E"

[colors.search.focused_match]
foreground = "#F5F1E8"
background = "#EF7C3E"

[colors.footer_bar]
foreground = "#F5F1E8"
background = "#B6603E"

[colors.hints.start]
foreground = "#F5F1E8"
background = "#EF7C3E"

[colors.hints.end]
foreground = "#F5F1E8"
background = "#B6603E"

[colors.selection]
text = "#F5F1E8"
background = "#D76D3C"

[colors.normal]
black = "#2D1F1A"
red = "#B6603E"
green = "#5A7A3A"
yellow = "#EF7C3E"
blue = "#3A5A7A"
magenta = "#7A4A6A"
cyan = "#3A7A7A"
white = "#703E3E"

[colors.bright]
black = "#5A3A2A"
red = "#D76D3C"
green = "#7A9A5A"
yellow = "#FFA347"
blue = "#5A7A9A"
magenta = "#9A6A8A"
cyan = "#5A9A9A"
white = "#5A2D2D"

[colors.dim]
black = "#1A1A1A"
red = "#8F4C3D"
green = "#3A5A2A"
yellow = "#B6603E"
blue = "#2A3A5A"
magenta = "#5A2A4A"
cyan = "#2A5A5A"
white = "#8F4C3D"