[colors.primary]
background = "#4A4030"
foreground = "#F0F0F0"
dim_foreground = "#D0D0D0"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#4A4030"
cursor = "#E0E0E0"

[colors.vi_mode_cursor]
text = "#4A4030"
cursor = "#FFFFFF"

[colors.search.matches]
foreground = "#4A4030"
background = "#D0D0D0"

[colors.search.focused_match]
foreground = "#4A4030"
background = "#F0F0F0"

[colors.footer_bar]
foreground = "#4A4030"
background = "#D0D0D0"

[colors.hints.start]
foreground = "#4A4030"
background = "#E0E0E0"

[colors.hints.end]
foreground = "#4A4030"
background = "#D0D0D0"

[colors.selection]
text = "#4A4030"
background = "#E0E0E0"

[colors.normal]
black = "#2A2A2A"
red = "#D0A060"
green = "#A0D060"
yellow = "#E0C060"
blue = "#8ABADD"
magenta = "#C08ABA"
cyan = "#8ACACA"
white = "#F0F0F0"

[colors.bright]
black = "#5A5A5A"
red = "#E0B070"
green = "#B0E070"
yellow = "#F0D070"
blue = "#9ACADD"
magenta = "#D09ACA"
cyan = "#9ADADA"
white = "#FFFFFF"

[colors.dim]
black = "#1A1A1A"
red = "#B08A50"
green = "#80B050"
yellow = "#C0A050"
blue = "#6A9ABB"
magenta = "#A06A9A"
cyan = "#6ABAAA"
white = "#D0D0D0"